import type { Metadata } from 'next'

import { Montserrat, Quicksand } from 'next/font/google'

import './globals.css'

const montserrat = Montserrat({
	variable: '--font-montserrat',
	subsets: ['latin'],
})

const quicksand = Quicksand({
	variable: '--font-quicksand',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${montserrat.variable} ${quicksand.variable} antialiased`}>{children}</body>
		</html>
	)
}
